"""Estrutura inicial limpa

Revision ID: 0b73d6bf6d65
Revises: 
Create Date: 2026-08-03 09:36:20.709678

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b73d6bf6d65'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('importacoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('arquivo', sa.String(length=255), nullable=False),
    sa.Column('periodo', sa.String(length=20), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('data_importacao', sa.DateTime(), nullable=False),
    sa.Column('registros', sa.Integer(), nullable=True),
    sa.Column('ativa', sa.Boolean(), nullable=False),
    sa.Column('observacao', sa.String(length=300), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cronograma_itens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('importacao_id', sa.Integer(), nullable=False),
    sa.Column('data', sa.String(length=10), nullable=False),
    sa.Column('dia_semana', sa.String(length=20), nullable=True),
    sa.Column('horario', sa.String(length=5), nullable=False),
    sa.Column('descricao', sa.String(length=300), nullable=False),
    sa.Column('executor', sa.String(length=100), nullable=True),
    sa.Column('cor', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('concluido', sa.Boolean(), nullable=True),
    sa.Column('observacao', sa.String(length=300), nullable=True),
    sa.ForeignKeyConstraint(['importacao_id'], ['importacoes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cronograma_itens')
    op.drop_table('importacoes')
    # ### end Alembic commands ###
