"""adiciona sistema aos itens do cronograma

Revision ID: 9506321c087b
Revises: 7b8d0f1c9a01
Create Date: 2026-08-12 20:27:18.711398

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9506321c087b'
down_revision = '7b8d0f1c9a01'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cronograma_itens', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sistema', sa.String(length=10), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cronograma_itens', schema=None) as batch_op:
        batch_op.drop_column('sistema')

    # ### end Alembic commands ###
