"""Adiciona registros e status na tabela importacoes

Revision ID: ac0befe9ee9d
Revises: 63769be7e1ed
Create Date: 2026-07-21 20:52:15.971024

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac0befe9ee9d'
down_revision = '63769be7e1ed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('importacoes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('registros', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('status', sa.String(length=30), nullable=True))
        batch_op.alter_column('tipo',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=20),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('importacoes', schema=None) as batch_op:
        batch_op.alter_column('tipo',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=10),
               existing_nullable=False)
        batch_op.drop_column('status')
        batch_op.drop_column('registros')

    # ### end Alembic commands ###
