"""Cria tabela configuracoes

Revision ID: c9951124f47f
Revises: 0b73d6bf6d65
Create Date: 2026-08-03 14:38:39.413092

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c9951124f47f'
down_revision = '0b73d6bf6d65'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('configuracoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('categoria', sa.String(length=50), nullable=False),
    sa.Column('chave', sa.String(length=100), nullable=False),
    sa.Column('valor_atual', sa.String(length=500), nullable=False),
    sa.Column('valor_padrao', sa.String(length=500), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('descricao', sa.String(length=255), nullable=True),
    sa.Column('editavel', sa.Boolean(), nullable=False),
    sa.Column('obrigatorio', sa.Boolean(), nullable=False),
    sa.Column('reiniciar', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('chave')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('configuracoes')
    # ### end Alembic commands ###
